name: heatstakes-gui
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pythonocc-core
  - pyqt  # Conda-forge resolverá la versión compatible (generalmente v5 o v6 adecuada)
  - numpy
  - pandas
  - scikit-learn